#!/bin/bash
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# Load other bashrc files
for bashrc_file in $(find "${script_dir}/bashrc.d" -type f | sort | grep -v ~$)
do
  if [ -n "${bashrc_file}" ]; then
    # shellcheck disable=SC1090
    source "${bashrc_file}"
  fi
done
