#!/bin/bash
# Create a Screen session everytime, unless you don't want

if [ -n "$(which screen)" ]; then
    if [ -n "${STY}" ]; then
        echo "This is screen session '${STY//[0-9]*\./}'"
    else
        echo "This is not a screen session, let's create one. Name of the session?"
        read -r session_name
        if [ -n "${session_name}" ] && [ "${session_name}" != "" ]; then
            if [ -n "$(which xtitle)" ]; then
                xtitle "${session_name}"
            else
                echo "xtitle is not installed so I can't update the title of the X window with the session name. Install it and the experience will be better)"
            fi
            screen -t "${session_name}" -S "${session_name}" && exit
        else
            echo "Ok, I'll leave you alone without a session..."
        fi
    fi
else
    echo "Screen is not installed. Install it so always_screen in your bashrc will work."
fi
