#!/bin/bash
if [ -z "${STY}" ]; then
    xtitle_cmd="$(which xtitle)"
    if [ -n "${xtitle_cmd}" ]; then
        new_title="${USER}@$(hostname -s)"
        echo "Setting title to ${new_title}"
        "${xtitle_cmd}" -q "${USER}@$(hostname -s)"
    fi
fi